artifact_uri: /work/users/ng739/cubesat/model/cubesat/yolo_model/runs/mlflow/711357490832256732/bc3aacbafa0c46e1aed5d94bf3f90afc/artifacts
end_time: 1776983028155
entry_point_name: ''
experiment_id: '711357490832256732'
lifecycle_stage: active
run_id: bc3aacbafa0c46e1aed5d94bf3f90afc
run_name: smoke_detection_20260423_171737
source_name: ''
source_type: 4
source_version: ''
start_time: 1776982671726
status: 3
tags: []
user_id: ng739
