artifact_location: /work/users/ng739/cubesat/model/cubesat/yolo_model/runs/mlflow/0
creation_time: 1776830701026
experiment_id: '0'
last_update_time: 1776830701026
lifecycle_stage: active
name: Default
workspace: default
